-- Atomik mesaj-claim tablosu: race-free duplicate tespiti.
-- Önceki "önce var mı diye SELECT'le bak, sonra INSERT et" deseni TOCTOU yarışına açıktı: iki
-- eşzamanlı istek (örn. ağ retry'ı) aynı anda "yok" görüp ikisi de NORMAL işlenebiliyordu.
-- Artık INSERT'in kendisi (UNIQUE constraint ihlali = "zaten var") atomik mutex görevi görüyor.
CREATE TABLE message_claims (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    module     INT NOT NULL,
    CONSTRAINT uq_message_claim UNIQUE (message_id, module)
);
