-- Atomic message-claim table: race-free duplicate detection.
-- The previous "SELECT to check if it exists, then INSERT" pattern was open to a TOCTOU race:
-- two concurrent requests (e.g. a network retry) could both see "not found" and both get
-- processed as NORMAL. Now the INSERT itself (UNIQUE constraint violation = "already exists")
-- acts as an atomic mutex.
CREATE TABLE message_claims (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    module     INT NOT NULL,
    CONSTRAINT uq_message_claim UNIQUE (message_id, module)
);
