-- Fraud initial schema (Flyway V1).
-- Column names match the schema produced by Hibernate's default snake_case strategy (messageId -> message_id).

CREATE TABLE transactions (
    id                  UUID PRIMARY KEY,
    message_id          BIGINT,
    module              INT,
    shadow_card_no      VARCHAR(64),
    amount              DECIMAL(19, 2),
    merchant_id         VARCHAR(64),
    transaction_date    TIMESTAMP WITH TIME ZONE,
    control_code        VARCHAR(20),
    fraud_response_code VARCHAR(40),
    latest_request      BOOLEAN
);
CREATE INDEX idx_tx_message_module ON transactions (message_id, module);

CREATE TABLE scenarios (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(200),
    product_type        VARCHAR(20),
    module              INT,
    priority            INT,
    fraud_response_code VARCHAR(40)
);
CREATE INDEX idx_scn_type_module ON scenarios (product_type, module);

CREATE TABLE rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200),
    type        VARCHAR(20),
    expression  VARCHAR(1000),
    scenario_id BIGINT,
    CONSTRAINT fk_rule_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id)
);

CREATE TABLE outbox_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(60),
    transaction_id      UUID,
    module              INT,
    fraud_response_code VARCHAR(40),
    tenant              VARCHAR(60),
    status              VARCHAR(20),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at        TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_outbox_status_created ON outbox_messages (status, created_at);
