-- Users for authentication: BCrypt password hashes + roles (RBAC).
-- Roles are stored comma-separated WITHOUT the ROLE_ prefix (e.g. 'ADMIN,USER');
-- Spring authorities get the prefix at token-validation time (JwtAuthenticationFilter).
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    roles         VARCHAR(200) NOT NULL,
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username)
);
