-- Persistent audit trail: who did what, when, under which correlation id.
-- Append-only; no update/delete path in the application.
CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    username       VARCHAR(100) NOT NULL,
    action         VARCHAR(60) NOT NULL,
    detail         VARCHAR(1000),
    correlation_id VARCHAR(64)
);
CREATE INDEX idx_audit_occurred ON audit_log (occurred_at);
