-- Server-side refresh tokens (rotation + reuse detection).
-- Only the SHA-256 hash of the token is stored — a DB leak exposes no usable tokens.
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    username   VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX idx_refresh_username ON refresh_tokens (username);
CREATE INDEX idx_refresh_expires  ON refresh_tokens (expires_at);
