# API Gateway konfigürasyonu

server:
  port: 8090

spring:
  application:
    name: payguard-gateway
  cloud:
    gateway:
      routes:
        # Tüm /api/** isteklerini arka API'ye (8080) ilet
        - id: internal-api
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
        # Actuator health'i de geçir
        - id: internal-actuator
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/**
      # Basit global CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,gateway
